pipeline {

   agent {
        label 'linux'
    }
environment {
        GITHUB_REPO = "https://github.com/Magik3a/Docker-Environments"              
        CONTAINER_NAME = "dotnetcore21_node10_npmserin"
        DOCKERFILE_PATH = "Linux/DotnetCore_21_Node10_NpmSerin/Dockerfile"
        VERSION = "1.0.0"
        REGISTRY_NAME = "s2kdesign"
        RESOURCE_GROUP_NAME = "s2kdesign"
        AZURE_CREDENTIALS_ID = "azure_service_principal"
        //git commit - works until you start supporting base image updates, where your build system will kick off, with the same git commit as the previous built. However, the base image will have new content. Using a git commit winds up being a semi-stable tag.
        // DEFAULT_IMAGE_NAME = "${CONTAINER_NAME}:${BRANCH_NAME_NORMALIZED}-${GIT_COMMIT.take(7)}"
        }
    stages {
       stage('Start Task in ACR - Master branch') {
            when {
                branch 'master'
            }
            steps{
                acrQuickTask azureCredentialsId:"${AZURE_CREDENTIALS_ID}", dockerfile:  "${DOCKERFILE_PATH}", gitPath: '', gitRefspec: '', gitRepo: "${GITHUB_REPO}", imageNames: [[image: "${CONTAINER_NAME}"], [image:"${CONTAINER_NAME}:${VERSION.split('\\.')[0]}.${BUILD_NUMBER}"]], registryName:"${REGISTRY_NAME}", resourceGroupName:  "${RESOURCE_GROUP_NAME}", tarball: '', variant: ''
            }
        }
        stage('Start Task in ACR - Deveop branch') {
            when {
                branch 'develop'
            }
            steps{
                acrQuickTask azureCredentialsId: "${AZURE_CREDENTIALS_ID}", dockerfile: "${DOCKERFILE_PATH}", gitPath: '', gitRefspec: '', gitRepo: "${GITHUB_REPO}", imageNames: [[image:"${CONTAINER_NAME}:${VERSION.split('\\.')[0]}.${VERSION.split('\\.')[1]}.${BUILD_NUMBER}"]], registryName: "${REGISTRY_NAME}", resourceGroupName:  "${RESOURCE_GROUP_NAME}", tarball: '', variant: ''
            }
        }
        stage('Start Task in ACR - Feature branch') {
             when { 
                branch "feature/*" 
             }
            steps{
               acrQuickTask azureCredentialsId: "${AZURE_CREDENTIALS_ID}", dockerfile: "${DOCKERFILE_PATH}", gitPath: '', gitRefspec: '', gitRepo:  "${GITHUB_REPO}", imageNames: [[image: "${CONTAINER_NAME}:${BRANCH_NAME.replaceAll("/", "-").toLowerCase()}"]], registryName: "${REGISTRY_NAME}", resourceGroupName: "${RESOURCE_GROUP_NAME}", tarball: '', variant: ''
        
            }
        }
    }
}